### ISSUE TITLE
[haxcms] Errors from migration

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#149]
- [x] #146 seems some kind of events getting lost issue
- [x] fix getSelection issues w/ shadow vs shadyDom
- [x] edit button on homepage does nothing (drop it for now)
- [x] edit should let you edit the title or have a way to modify the page internals (#155 could help in forging a path to this)
- [x] add an "add page" button
- [x] buttons dont show on top level page when logged in (page must be in scope)
- [x] #151 
- [x] move haxcms-site-editor-ui to be global when it's called for to avoid stack order issues
- [x] https://github.com/PolymerElements/paper-dialog/issues/135 selecting something in a dropdown in simple-modal will close the modal (which is common in haxcms modals). Swap these out with Nikki's simple-picker (may need this to be wired into json schema to achieve)

**Comment by btopro** [comment]
Much of these seem to stem from shadowRoots vs completely open event bubbling. We may need something in HaxStore that's an object keeping track of who the direct parent that implemented hax-body is. If we have this information then we could back track to get the appropriate selection.

We may need something such as w`indow.HaxStore.instance.activeHaxBody.parentNode.parentNode.getSelection();` or basically stepping up from HaxBody until we run into a shadowRoot fragment then allowing us to get the active selection appropriately.

If we don't run into that then we should fallback to window.selection (which would imply shadyDOM and it'll just work... i think).

This is true of ALL text based operations (bleh)
